system-port: 7890
external-controller: 127.0.0.1:9090
allow-lan: false
mode: rule
log-level: info
ipv6: true
unified-delay: true
profile:
  store-selected: true
  store-fake-ip: true
tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
dns:
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - 223.5.5.5
    - 8.8.8.8
proxies:
  - name: ARTS-R2-JP
    type: hysteria2
    server: 31.57.172.132
    port: 1741
    password: MurphyNeveu#34494=
    sni: bing.com
    skip-cert-verify: true
  - name: SHU OpenVPN
    type: socks5
    server: 210.16.170.212
    port: 4080
proxy-groups:
  - name: Auto
    type: select
    proxies:
      - ARTS-R2-JP
      - SHU OpenVPN
rules:
  - DOMAIN-SUFFIX,shu.edu.cn,SHU OpenVPN
  - GEOIP,CN,DIRECT
  - DOMAIN-KEYWORD,comic,DIRECT
  - DOMAIN-KEYWORD,jm,DIRECT
  - DOMAIN-SUFFIX,zoot.plus,DIRECT
  - DOMAIN-SUFFIX,maa.plus,DIRECT
  - DOMAIN-KEYWORD,mexc,Auto
  - DOMAIN-KEYWORD,zerossl,Auto
  - DOMAIN-KEYWORD,betterstack,DIRECT
  # - DOMAIN-KEYWORD,cloudflare,auto
  - DOMAIN-SUFFIX,ea.com,DIRECT
  - DOMAIN-SUFFIX,tnt-ea.com,DIRECT
  - MATCH,Auto
